name: Q2 - Archive TOTO.txt avec Métadonnées

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  archive-enhanced:
    runs-on: ubuntu-latest
    env:
      NOM_PRENOM: "AlphaSaiiko"
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Collecter les informations
        id: info_collector
        run: |
          
          DATE_TIME=$(date +'%Y-%m-%d %H:%M:%S')
          echo "date_time=$DATE_TIME" >> $GITHUB_OUTPUT
          
          
          TOTO_SIZE=$(wc -c < TOTO.txt | awk '{print $1}')
          echo "toto_size=$TOTO_SIZE octets" >> $GITHUB_OUTPUT

      - name: Créer Q2_archive_TOTO.txt
        run: |
          echo "Archive créée par : $NOM_PRENOM" > Q2_archive_TOTO.txt
          echo "Date et heure d'exécution : ${{ steps.info_collector.outputs.date_time }}" >> Q2_archive_TOTO.txt
          echo "-----------------------------------" >> Q2_archive_TOTO.txt
          echo "Contenu de TOTO.txt :" >> Q2_archive_TOTO.txt
          cat TOTO.txt >> Q2_archive_TOTO.txt
          echo "-----------------------------------" >> Q2_archive_TOTO.txt
          echo "Taille de TOTO.txt : ${{ steps.info_collector.outputs.toto_size }}" >> Q2_archive_TOTO.txt

      - name: Pousser le fichier archivé
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Q2: Ajout de Q2_archive_TOTO.txt (workflow Q2)'
          file_pattern: Q2_archive_TOTO.txt
